// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo-service.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ToDo struct {
	Id          int64  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	// Date and time to reminder
	Reminder *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=reminder" json:"reminder,omitempty"`
}

func (m *ToDo) Reset()                    { *m = ToDo{} }
func (m *ToDo) String() string            { return proto.CompactTextString(m) }
func (*ToDo) ProtoMessage()               {}
func (*ToDo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ToDo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ToDo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ToDo) GetReminder() *google_protobuf.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	// Task entity to add
	ToDo *ToDo `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

type CreateResponse struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ReadRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadResponse struct {
	Api  string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	ToDo *ToDo  `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

type UpdateRequest struct {
	Api  string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	ToDo *ToDo  `protobuf:"bytes,2,opt,name=toDo" json:"toDo,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetToDo() *ToDo {
	if m != nil {
		return m.ToDo
	}
	return nil
}

type UpdateResponse struct {
	Api     string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Updated int64  `protobuf:"varint,2,opt,name=updated" json:"updated,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResponse struct {
	Api     string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	Deleted int64  `protobuf:"varint,2,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type ReadAllRequest struct {
	Api string `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
}

func (m *ReadAllRequest) Reset()                    { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()               {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ReadAllResponse struct {
	Api   string  `protobuf:"bytes,1,opt,name=api" json:"api,omitempty"`
	ToDos []*ToDo `protobuf:"bytes,2,rep,name=toDos" json:"toDos,omitempty"`
}

func (m *ReadAllResponse) Reset()                    { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()               {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetToDos() []*ToDo {
	if m != nil {
		return m.ToDos
	}
	return nil
}

func init() {
	proto.RegisterType((*ToDo)(nil), "v1.ToDo")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "v1.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "v1.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "v1.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "v1.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "v1.DeleteResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "v1.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "v1.ReadAllResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ToDoService service

type ToDoServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type toDoServiceClient struct {
	cc *grpc.ClientConn
}

func NewToDoServiceClient(cc *grpc.ClientConn) ToDoServiceClient {
	return &toDoServiceClient{cc}
}

func (c *toDoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toDoServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := grpc.Invoke(ctx, "/v1.ToDoService/ReadAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ToDoService service

type ToDoServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

func RegisterToDoServiceServer(s *grpc.Server, srv ToDoServiceServer) {
	s.RegisterService(&_ToDoService_serviceDesc, srv)
}

func _ToDoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToDoService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ToDoService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ToDoService",
	HandlerType: (*ToDoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ToDoService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ToDoService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ToDoService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ToDoService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ToDoService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo-service.proto",
}

func init() { proto.RegisterFile("todo-service.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x31, 0x6f, 0xd3, 0x40,
	0x18, 0x95, 0xed, 0x34, 0x6d, 0xbf, 0x34, 0x49, 0x7b, 0x05, 0x11, 0x59, 0x15, 0x58, 0x9e, 0xaa,
	0x88, 0xd8, 0x8d, 0x89, 0x3a, 0x84, 0x8a, 0xb6, 0x34, 0x20, 0x75, 0x35, 0x65, 0x81, 0xe9, 0x6a,
	0x1f, 0xce, 0x21, 0xc7, 0x67, 0x7c, 0x97, 0x14, 0x84, 0xba, 0x30, 0xb0, 0xb1, 0xc0, 0xc6, 0xdf,
	0x42, 0x62, 0x60, 0xe6, 0x87, 0x20, 0xdf, 0xd9, 0x6d, 0x9c, 0x36, 0x5d, 0x98, 0x92, 0xfb, 0xee,
	0x7d, 0xef, 0xbd, 0xcf, 0xef, 0xee, 0x00, 0x09, 0x16, 0xb2, 0x1e, 0x27, 0xd9, 0x8c, 0x06, 0xc4,
	0x49, 0x33, 0x26, 0x18, 0xd2, 0x67, 0x7d, 0xf3, 0x51, 0xc4, 0x58, 0x14, 0x13, 0x57, 0x56, 0xce,
	0xa7, 0xef, 0x5c, 0x41, 0x27, 0x84, 0x0b, 0x3c, 0x49, 0x15, 0xc8, 0xdc, 0x29, 0x00, 0x38, 0xa5,
	0x2e, 0x4e, 0x12, 0x26, 0xb0, 0xa0, 0x2c, 0xe1, 0xc5, 0xee, 0x63, 0xf9, 0x13, 0xf4, 0x22, 0x92,
	0xf4, 0xf8, 0x05, 0x8e, 0x22, 0x92, 0xb9, 0x2c, 0x95, 0x88, 0x9b, 0x68, 0xfb, 0xab, 0x06, 0xb5,
	0x33, 0x36, 0x62, 0xa8, 0x05, 0xfa, 0x69, 0xd8, 0xd1, 0x2c, 0x6d, 0xd7, 0xf0, 0xf5, 0xd3, 0x10,
	0xdd, 0x83, 0x95, 0x33, 0x2a, 0x62, 0xd2, 0xd1, 0x2d, 0x6d, 0x77, 0xdd, 0x57, 0x0b, 0x64, 0x41,
	0x63, 0x44, 0x78, 0x90, 0x51, 0x49, 0xd8, 0x31, 0xe4, 0xde, 0x7c, 0x09, 0xed, 0xc3, 0x5a, 0x46,
	0x26, 0x34, 0x09, 0x49, 0xd6, 0xa9, 0x59, 0xda, 0x6e, 0xc3, 0x33, 0x1d, 0xe5, 0xd7, 0x29, 0x07,
	0x72, 0xce, 0xca, 0x81, 0xfc, 0x2b, 0xac, 0x7d, 0x08, 0xcd, 0x93, 0x8c, 0x60, 0x41, 0x7c, 0xf2,
	0x61, 0x4a, 0xb8, 0x40, 0x9b, 0x60, 0xe0, 0x94, 0x4a, 0x47, 0xeb, 0x7e, 0xfe, 0x17, 0xed, 0x40,
	0x4d, 0xb0, 0x11, 0x93, 0x8e, 0x1a, 0xde, 0x9a, 0x33, 0xeb, 0x3b, 0xb9, 0x75, 0x5f, 0x56, 0x6d,
	0x0f, 0x5a, 0x25, 0x01, 0x4f, 0x59, 0xc2, 0xc9, 0x2d, 0x0c, 0x2d, 0xd0, 0x69, 0x28, 0xfb, 0x0d,
	0x5f, 0xa7, 0xa1, 0xed, 0x42, 0xc3, 0x27, 0x38, 0x5c, 0x2e, 0xb9, 0xd8, 0xf0, 0x0c, 0x36, 0x54,
	0xc3, 0x52, 0x89, 0xbb, 0x4d, 0x1e, 0x42, 0xf3, 0x75, 0x1a, 0xfe, 0xc7, 0x94, 0x07, 0xd0, 0x2a,
	0x09, 0x96, 0x5a, 0xe8, 0xc0, 0xea, 0x54, 0x62, 0x4a, 0xe7, 0xe5, 0xd2, 0xee, 0x43, 0x73, 0x44,
	0x62, 0x72, 0x97, 0xfc, 0xe2, 0xc4, 0x07, 0xd0, 0x2a, 0x5b, 0xee, 0x12, 0x0c, 0x25, 0xe6, 0x4a,
	0xb0, 0x58, 0xda, 0x36, 0xb4, 0xf2, 0xef, 0x75, 0x1c, 0xc7, 0x4b, 0x15, 0xed, 0x13, 0x68, 0x5f,
	0x61, 0x96, 0x4a, 0x3c, 0x84, 0x95, 0x7c, 0x7e, 0xde, 0xd1, 0x2d, 0xa3, 0xf2, 0x59, 0x54, 0xd9,
	0xfb, 0x66, 0x40, 0x23, 0x5f, 0xbf, 0x52, 0xd7, 0x09, 0x8d, 0xa0, 0xae, 0x4e, 0x03, 0xda, 0xca,
	0xa1, 0x95, 0xa3, 0x65, 0xa2, 0xf9, 0x92, 0x92, 0xb4, 0xb7, 0xbf, 0xfc, 0xfa, 0xfb, 0x43, 0x6f,
	0xda, 0x6b, 0xee, 0xac, 0xef, 0xe6, 0x37, 0x73, 0xa8, 0x75, 0xd1, 0x11, 0xd4, 0x72, 0x6b, 0xa8,
	0x9d, 0x37, 0xcc, 0x9d, 0x14, 0x73, 0xf3, 0xba, 0x50, 0xf4, 0xdf, 0x97, 0xfd, 0x6d, 0xd4, 0x2c,
	0xfb, 0xdd, 0xcf, 0x34, 0xbc, 0x44, 0x11, 0xd4, 0x55, 0x5e, 0xca, 0x47, 0x25, 0x7c, 0xe5, 0xa3,
	0x1a, 0xa7, 0xbd, 0x2f, 0x79, 0xf6, 0x4c, 0x74, 0xcd, 0x93, 0x4f, 0xe8, 0x9c, 0x86, 0x97, 0x43,
	0xad, 0xfb, 0xe6, 0x81, 0x77, 0xfb, 0x06, 0x7a, 0x09, 0x75, 0x95, 0x93, 0x12, 0xaa, 0xc4, 0xac,
	0x84, 0xaa, 0x31, 0x96, 0x86, 0xbb, 0x0b, 0x86, 0x5f, 0xc0, 0x6a, 0x91, 0x06, 0x42, 0xe5, 0x90,
	0xd7, 0xf1, 0x99, 0xdb, 0x95, 0x5a, 0x41, 0xb5, 0x25, 0xa9, 0x1a, 0x68, 0xbd, 0xa4, 0xe2, 0xcf,
	0xff, 0x68, 0xdf, 0x8f, 0x7f, 0x6b, 0x28, 0x85, 0x8d, 0x3c, 0x15, 0xab, 0x78, 0xe5, 0xec, 0xb7,
	0xd0, 0x8e, 0x58, 0x2f, 0xca, 0xd2, 0xa0, 0x17, 0x61, 0x41, 0x2e, 0xf0, 0x27, 0xe4, 0x8c, 0x85,
	0x48, 0xf9, 0xd0, 0x75, 0x23, 0x2a, 0xc6, 0xd3, 0x73, 0x27, 0x60, 0x13, 0x37, 0xc0, 0x6c, 0xcc,
	0x70, 0x12, 0x25, 0x78, 0xe2, 0x2e, 0xe0, 0xcd, 0xce, 0xdc, 0x66, 0xbf, 0x3f, 0x38, 0x8a, 0x26,
	0x98, 0xc6, 0x79, 0x97, 0x67, 0xf4, 0x9d, 0xbd, 0xae, 0xa6, 0x79, 0x9b, 0x38, 0x4d, 0x63, 0x1a,
	0xc8, 0x77, 0xce, 0x7d, 0xcf, 0x59, 0x32, 0xbc, 0x51, 0xf1, 0x9f, 0x82, 0x31, 0xd8, 0x1b, 0xa0,
	0x01, 0x74, 0x7d, 0x22, 0xa6, 0x59, 0x42, 0x42, 0xeb, 0x62, 0x4c, 0x12, 0x4b, 0x8c, 0x89, 0x95,
	0x11, 0xce, 0xa6, 0x59, 0x40, 0xac, 0x90, 0x11, 0x6e, 0x25, 0x4c, 0x58, 0xe4, 0x23, 0xe5, 0xc2,
	0x41, 0x75, 0xa8, 0xfd, 0xd4, 0xb5, 0xd5, 0xf3, 0xba, 0x7c, 0xc9, 0x9e, 0xfc, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0xea, 0xbe, 0x53, 0x82, 0xc2, 0x05, 0x00, 0x00,
}
